name: RandomWalkingBlock
version: 1.0.0
api-version: '1.20'
main: com.noobnuby.plugin.Main
description: Minecraft plugin that randomly changes blocks as you walk
website: https://me.noobnuby.com
author: noobnuby
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0